services:
  - type: web
    name: quickload
    runtime: docker
    plan: free

    startCommand: |
      php artisan migrate --force
      apache2-foreground

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://quickload.onrender.com
      - key: APP_KEY
        generateValue: true

      # Aiven MySQL Database Configuration
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-195892ed-techengineguy-ae50.j.aivencloud.com
      - key: DB_PORT
        value: 13420
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_yXHhbL5BBUWL39hdSZX
      - key: DB_SSL
        value: true
      - key: DB_SSL_CA
        value: storage/certs/aiven-ca.pem

      # Laravel Session & Cache Drivers
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
