services:
  - type: web
    name: quickload
    runtime: docker
    plan: free
    buildCommand: docker build -t quickload .
    startCommand: docker run -p 10000:8080 quickload
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://quickload.onrender.com
      - key: APP_KEY
        generateValue: true  # Auto-generates Laravel key