services:
  - type: web
    name: quickload
    runtime: docker
    plan: free

    startCommand: |
      apache2-foreground

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://quickload.onrender.com
      - key: APP_KEY
        generateValue: true

      # Aiven MySQL Database Configuration
      - key: DB_CONNECTION
        value: null
      - key: DB_HOST
        value: sql8.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: sql8785882
      - key: DB_USERNAME
        value: sql8785882
      - key: DB_PASSWORD
        value: 3TXXDPV79u
      

      # Laravel Session & Cache Drivers
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
