services:
  - type: web
    name: quickload
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://quickload.onrender.com
      - key: APP_KEY
        generateValue: true  # Auto-generates Laravel key